[package]
name = "playmd"
version = "0.1.0"
authors = ["Shotaro Tsuji <Shotaro.Tsuji@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.8.0"
trim-in-place = "0.1.5"
eyre = "*"

[dev-dependencies]
structopt = "0.3.21"
