[book]
authors = ["岡本かの子"]
language = "ja"
multilingual = false
src = "src"
title = "取返し物語"

[preprocessor.playscript]
command = "../../target/debug/mdbook-playscript"
japanese-ruby.enable = true
counting.enable = true

[output.html]
additional-css = ["mdplayscript_ja.css"]
additional-js = ["playscript-count.js"]
search.enable = false
