name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.6'

    - name: Build mdBook (Figaro)
      run: mdbook build
      working-directory: examples/figaro
    - name: Build mdBook (Torikaeshi)
      run: mdbook build
      working-directory: examples/torikaeshi

    - name: Deploy mdBook (Figaro)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./examples/figaro/book
        destination_dir: figaro
    - name: Deploy mdBook (Torikaeshi)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./examples/torikaeshi/book
        destination_dir: torikaeshi
